name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish to npmjs.org
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          if [ "$(jq -r .version < package.json)" != "$(npm view nvd-search version)" ]; then
            npm publish
          else
            echo "package.json and latest published version are the same."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
